//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCInsight.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAdminUser
    {
        public int admin_id { get; set; }
        public string loginId { get; set; }
        public string password { get; set; }
        public string fullName { get; set; }
        public string userType { get; set; }
        public bool isActive { get; set; }
    }
}
