//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCInsight.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblAdminLog
    {
        public int LogId { get; set; }
        public string SectionName { get; set; }
        public string ModuleName { get; set; }
        public string Action { get; set; }
        public string FileName { get; set; }
        public string Description { get; set; }
        public System.DateTime LogDate { get; set; }
        public int UserId { get; set; }
        public string Ip { get; set; }
    }
}
