//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCInsight.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAttendance
    {
        public int id { get; set; }
        public Nullable<int> salePersonNo { get; set; }
        public Nullable<System.DateTime> AttendanceDate { get; set; }
        public string status { get; set; }
        public string firstintime { get; set; }
        public string secondouttime { get; set; }
        public string thirdintime { get; set; }
        public string fourthouttime { get; set; }
        public string totalHours { get; set; }
    }
}
