//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCInsight.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBrand
    {
        public int brand_id { get; set; }
        public string brandName { get; set; }
        public string locationGrade { get; set; }
        public string zoneName { get; set; }
        public Nullable<int> wallSpace { get; set; }
        public Nullable<int> height { get; set; }
        public string brandCategory { get; set; }
    }
}
