//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCInsight.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMultiBrandIncentiveRule
    {
        public int RuleId { get; set; }
        public string RuleName { get; set; }
        public string SiteCuid { get; set; }
        public string Dpeartment { get; set; }
        public string Brand { get; set; }
        public string Section { get; set; }
        public string Product { get; set; }
        public string StyleCode { get; set; }
        public decimal IncentiveAmount { get; set; }
        public Nullable<System.DateTime> ActiveFrom { get; set; }
        public Nullable<System.DateTime> ActiveTo { get; set; }
        public bool IsActive { get; set; }
    }
}
