//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCInsight.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPvtLabelGroup
    {
        public int id { get; set; }
        public Nullable<int> groupId { get; set; }
        public string department { get; set; }
        public string brandName { get; set; }
        public string product { get; set; }
    }
}
