//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCInsight.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSite
    {
        public int site_id { get; set; }
        public string site_cuid { get; set; }
        public string site_name { get; set; }
        public string site_location { get; set; }
        public string site_city { get; set; }
        public string site_email { get; set; }
        public string contact_no { get; set; }
    }
}
