//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCInsight.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSiteSetting
    {
        public int SettingId { get; set; }
        public string AdminEmail { get; set; }
        public string AdminMobile { get; set; }
        public string ApiVersion { get; set; }
        public string EnableSmsNotification { get; set; }
        public string SmsUrl { get; set; }
        public string SmsUserName { get; set; }
        public string SmsPassword { get; set; }
        public string SmsApiKey { get; set; }
    }
}
