//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCInsight.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblstock
    {
        public int stock_id { get; set; }
        public string barcode { get; set; }
        public int site_id { get; set; }
        public int div_id { get; set; }
        public int sec_id { get; set; }
        public int dep_id { get; set; }
        public int brand_id { get; set; }
        public string styleCode { get; set; }
        public int color_id { get; set; }
        public int size_id { get; set; }
        public string fit { get; set; }
        public int closingTotal { get; set; }
        public string combination { get; set; }
        public string siteCuid { get; set; }
        public string category2 { get; set; }
        public string desc4 { get; set; }
        public string desc6 { get; set; }
        public string mrp { get; set; }
        public string vendorName { get; set; }
        public Nullable<System.DateTime> lastStockUpdate { get; set; }
    }
}
