//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCInsight.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSlab
    {
        public int id { get; set; }
        public System.DateTime lastUpdate { get; set; }
        public int salesPersonNo { get; set; }
        public string finYear { get; set; }
        public int qtrNo { get; set; }
        public int slabNo { get; set; }
        public decimal slabAmount { get; set; }
        public decimal monthlyIncentive { get; set; }
    }
}
