//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCInsight.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVendorsalesperson
    {
        public int Id { get; set; }
        public Nullable<int> id_vendor { get; set; }
        public string site_cuid { get; set; }
        public string department { get; set; }
        public string brand { get; set; }
        public Nullable<int> sales_person_no { get; set; }
        public Nullable<System.DateTime> insert_date { get; set; }
        public Nullable<System.DateTime> last_update_date { get; set; }
    }
}
