//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCInsight.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWeeklytargetincentive
    {
        public int id { get; set; }
        public int salesPersonNo { get; set; }
        public string finYear { get; set; }
        public int weekNo { get; set; }
        public long weekTargetAmt { get; set; }
        public decimal incentivePercent { get; set; }
        public decimal weekSalesAmt { get; set; }
        public decimal incentiveEarnedAmt { get; set; }
        public Nullable<System.DateTime> dateEntered { get; set; }
        public Nullable<System.DateTime> lastUpdatedDate { get; set; }
        public Nullable<System.DateTime> lastCalcDate { get; set; }
    }
}
